<?php

/* @var $this yii\web\View */

$this->title = 'Autobiograffiti of Grandville Rodriquez';
use yii\helpers\Html;
?>
<!DOCTYPE html>
<html>
    <body>
        <div class = "title">
            <h3>
                The Autobiograffiti of Grandville Rodriquez:
            </h3>
            <h4>The Outlaw that Saved the World</h4>
        </div>
        <div class = "container">
            <div class = "row">
                <div class = "col-md">
                    <div class = "story">
                        <div class = "container col-md-6 spacer">
                            <?= html::img('images/GRCover.png', ['alt' => "some", "class" => "img-responsive"])?>
                            </div>
                        <h3>
                            <p>I've got a loving wife, three step kids, two of which think I'm a God, a nice union job, and guess what?</p>
                        </h3>
                        <p>The IRS thinks I'm a tax dodger and the FBI has wired my house with cameras and microphones.</p>

                        <p>I know why. I'm Mexican. Mexicans are rapist and serial killers and only take their pay in cash. The gringo needs to be on constant alert for the next Mexican felony.</p>

                        <p>My name is Grandville Rodriquez and if the gringo likes to worry about Mexicans, then I might just give the gringo something to really worry about.</p>

                        <p class="p1"><span class="s1">Foreward by President of the United States, Jimmy Allen, in collaboration with Granville's stepdaughter, Josephina Rodriquez-Alvares, in the year AAD 25 (After the Alien Departed).</span></p>
                        <p class="p2"><span class="s1">GRANDVILLE RODRIQUEZ </span></p>
                        <p class="p2"><span class="s1">THE AMAZING STORY OF THE OUTLAW THAT SAVED THE WORLD</span></p>
                        <p class="p1"><span class="s1"><span class="Apple-converted-space">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span>Grandville Rodriquez was born on the banks of the Los Angeles River, October 25, 1941, the very day his mother, Rebecca Alonzo, age sixteen, was smuggled over the Mexican border. Coming from the rural areas of Sonora, Mexico, Rebecca was aghast at the immensity of Los Angeles while peeking through the slats of a cattle truck. She decided to name her first born Villa Grande Elias Rodriquez. Villa Grande (&ldquo;huge city&rdquo;) was later Americanized to Grandville.</span></p>
                        <p class="p1"><span class="s1">Grandville's first glimpse of Earth was of a newborn oil well, gushing oil into the sky on a stifling hot October day. Grandville's eyes rolled with the flight of the black rain as it gently fell into the Los Angeles River, forcing the slow moving animal parts from the nearby slaughterhouse to curl into black paste along the river shoreline.</span></p>
                        <p class="p1"><span class="s1">His stomach churned. It is thus understandable that he began suffering a strange intestinal disorder soon after birth, which nearly brought him to death and forced him to restrain from all foods except rotten bananas and soy milk, until the age of five. Apparently soybeans and black bananas produced enzymes that eventually were accepted by his terrorized stomach. However, soybeans and rotten bananas have their drawbacks. They lack vitamin D and C. Thus Grandville suffered from rickets and scurvy in his preschool years and spent a good spell of his young life in the bathroom.</span></p>
                        <p class="p1"><span class="s1">Grandville's mother said that despite his painful asshole and stomach, Grandville was an amazingly happy baby and rarely, if ever, cried. However, because of his early sicknesses, there were concerns in his family, which included a grandmother and a younger brother, that Grandville was retarded. Grandville attended the Bellview Retard School until the age of eight for he talked only in babbles his first seven years and never quite mastered the art of walking.</span></p>
                        <p class="p1"><span class="s1">Grandville remembers the first words he said that were understood. The event occurred at age six while he was recovering from an accident where his penis had been severed while he was playing with playpen clamps. After the operation of sewing his penis back on, a nurse in the hospital, unaware he couldn't talk, came in and asked Grandville what he wanted for breakfast. Grandville recalls he said, &ldquo;I want Rice Krispies.&rdquo;</span></p>
                        <p class="p1"><span class="s1">It should be noted that despite his native language, Spanish, being spoken exclusively in his home, his first understandable words were in his emphasized English as he not only over-pronounced certain words but he also, at times, pronounced each syllable individually&mdash;a trait that was to stay with him all of his life. As much to the chagrin of the Chicano population of Los Angeles, Grandville never spoke in Spanish and considered Chicanos who tried to hold on to one gringo language over another as people who had lost their mind. Grandville noticed early that if you were Mexican in America, you needed to speak English or beg for an early death.</span></p>
                        <p class="p1"><span class="s1">As a child he had no friends and few inclinations, retreating into his room after school and studying the almanac. It is said at age eight when his family visited an uncle in Santa Fe, New Mexico, Grandville boldly attempted to walk, waddling up and down the aisles of the train, announcing at the top of his lungs, &ldquo;I am eight years old and I know everything there is to know. I know my name: Villa Grande Elias Rodriquez. And I know the population of every city we are passing.&rdquo; Grandville, an almanac expert, proceeded to announce the exact population of every city the train passed. Riders were shocked when they saw the population sign before the entrance to every city; Grandvllle was exactly correct.</span></p>
                        <p class="p1"><span class="s1">Despite his cockiness, Grandville did very poorly in school and after a temper tantrum in his high school physics class, combined with his .05 grade average, the school encouraged Grandville to drop out and get his GED. But he refused. He had something to teach his teacher: he did not like his physics teacher's gravity theory that had little balls romping around bigger balls with nothing whatsoever tying them together. Grandville was convinced that the motion of the larger bodies in space-time displaced space-time creating vacuum cracks and these cracks sucked smaller bodies around larger bodies, which his teacher misinterpreted as gravity. To disprove his teacher, Grandville built his science project, showcasing a giant carburetor that caused enough smog for a full day in LA, a vacuum cleaner the size of a semi and seven various size balls on engine-propelled model airplanes&mdash;all of which could only fit on the football field. The experiment resulted in an F when the biggest of these balls collided into the chest of the teacher, causing a premature death.</span></p>
                        <p class="p1"><span class="s1">Given the choice of the army or jail, Grandville was assigned the MOS of an infantry soldier and sent to guard the Korean DMZ during the postwar period. People who recall Grandville in the army say he appeared to be in a stupor most of the time and developed the habit of laughing in front of his superiors when they were loudly proclaiming their demands, the worst possible moment to laugh if you were in the military. Grandville, himself, recalls the horrors of the infantry, such as the frightening 6 a.m. jogs through the shit-filled rice paddies and the weekly bayonet assault course that required sprinting up steep mountains, which Grandville actually just waddled up, and sticking bayonets into scores of scarecrows in the muggy heat of the Korean summer. These types of activities forced Grandville into the orderly room in the wee small hours of the night and there he practiced typing, which earned him a job as company clerk, thus saving him from the horrors of being an infantry soldier.</span></p>
                        <p class="p1"><span class="s1">It is astounding to his family that despite his lack of education and suspected intelligence deficiencies, soon out of the army, Grandville married the famous Danish physicist, Janne Thousig, and moved to Copenhagen, Denmark. However, this turned out to be an unfortunate marriage as Grandville's mother-in-law considered him to be a stumbling, sloppy, belly-hanging idiot who looked like an overstuffed bird and spent more time waddling to the bathroom than to work. But Grandville did work, building elaborate electrical devices that produced painful shocks, which made it impossible for his mother-in-law to barge into the newlyweds' home unanounced. Nevertheless, these six months, before his wife decided that she loved her mother more than Grandville, proved to play an important role in Grandville's incredible impact upon world history.</span></p>
                        <p class="p1"><span class="s1">Moving back to Los Angeles, his second marriage to Francie Zweigart, a veterinarian, proved equally unfortunate. During this short marriage, Grandville developed the intense dislike of animals as his new wife's compassionate heart amassed huge quantities of animals and fleas. The animals were the worst as they not only bit, but also pissed and shitted on the furniture, forcing Grandville's rapid departure.</span></p>
                        <p class="p1"><span class="s1">But it was Grandville's third marriage that provided the most motivation for his incredible feat. This woman, a Gertrude Eddington, was a lawyer who continually prodded Grandville to become rich and insisted on having the most prestigious models of automobiles. Much to the surprise of his family, during this period, Grandville became quite successful, creating a chain of junk food grocery stores that grossed over a hundred million a year. But to his family's surprise, Grandville disappeared one day, leaving behind his third wife, their plush home and assorted luxurious automobiles, as well as his healthy, junk food grocery store chain.</span></p>
                        <p class="p1"><span class="s1">Then, suddenly after twelve years of hiding from the F.B.I., he was discovered in Canoga Park, California, with his fourth wife and her three kids from a love affair she had in her early teens.</span></p>
                        <p class="p1"><span class="s1">Grandville Rodriquez became the greatest Mexican hero of all time, first creating the underground banking system, La Raza, which offered loans with no collateral to Latinos and at zero percent interest rates. Second, he made money worthless, destroying the gringo power structure and finally, when the gringo's response was nuclear destruction of the world, he aborted their efforts. And now, Grandville, the savior of the common people of the world, has created his own museum calling it the Autobiograffiti of Grandville Rodriquez, which is a three-mile line of sign posts in the Norfolk Island Pine Forest of Kaua'i, revealing all the lies the gringo world has been telling you about him and his reasoning behind his incredible feat.</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p3">&nbsp;</p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">. </span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p2"><span class="s1">We begin the walk through Grandville's Museum. The first 801 sign posts at the beginning of this museum contain only biblical sayings that may or may not reflect the new &ldquo;Spotlight to Heaven&rdquo; religion.<span class="Apple-converted-space">&nbsp; </span>We feel this is the best place to start.<span class="Apple-converted-space">&nbsp; </span>We begin with sign post 886. </span></p>
                        <p class="p4">&nbsp;</p>
                        <p class="p1"><span class="s1">Canoga Park, California, April 1980</span></p>
                        <p class="p1"><span class="s1">THE NO-MONEY EXPERIMENT BEGINS</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">Grandville, now at the age of thirty-eight, sits flopped out on his double-cushioned leather chair, aimlessly staring at the boob tube with his age-old companion: a six-pack of Beer securely nestled in his lap. He opens another one and contemplates the attributes of degenerating. A philosopher at heart, he reasons that degenerating is especially good after a day at work, but to degenerate without working is not as blissful. Grandville decides to show up to work tomorrow.</span></p>
                        <p class="p1"><span class="s1">The evening news is reporting on the new $1.8 billion federal loan to Chrysler. Cars remind Grandville of burnt, brown formaldehyde skies and his third wife. Laying the remains of his six-pack on the floor, Grandville is stewed out of his degenerative state enough to stumble toward the TV and shut it off with a blow of his fist.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Why is it,&rdquo; he bellows, &ldquo;that God cursed me with being the only sane person in this lunatic world?&rdquo; He stares at the ceiling. He can hear his wife in the kitchen and decides to take comfort with her.</span></p>
                        <p class="p1"><span class="s1">Grandville's fourth wife Alice is a brazen, forceful lady, full of enthusiasm, and she absolutely idolizes her man. She believes his claims that he can perform miracles anytime he wants, but that he now prefers to degenerate instead. This is probably because of his many miracles that people actually pay him for, plus his miracle tendencies in bed due to his passionate nature and a crooked penis that seems to gravitate to the perfect spot. Grandville, himself , is intensely pleased with this wife. She loves spoiling him and he loves to be spoiled. She listens to his wild philosophies, his radical cosmic theories, and tells him that he is going to be famous one day, that the world will long remember his name. Grandville has always suspected this, but Alice is the first person in his life to confirm his suspicions. She even loves his gently protruding beer belly and the way he stumbles around with a walk that goes sideways and slightly forward at the same time.</span></p>
                        <p class="p1"><span class="s1">When he enters the kitchen, she gives him a hug, a smile and a wrench to the floor, aggressively trying to make love with her clothes on as the kids play in their bedrooms. Finally, she eases up, smiles and asks if she can draw a bath for him. Grandville acquiesces while checking out the pre-dinner munchies, she goes to arrange his bath. Again, Grandville drifts back into one of his famed philosophical moods, thinking his life might be getting too easy, that it might be time to toughen things up a bit.</span></p>
                        <p class="p1"><span class="s1">When Alice calls him to the bath and he arrives, she drags him in and locks the door, undressing herself then him, kissing him here and there, and sucking on that crooked cock. Grandville then does her against the bathroom wall. It always amazed him how she can so completely let go. It is like she melts right through him. Then, blushing, she shyly struggles back into her clothes and leaves him with his hot drawn bath.</span></p>
                        <p class="p1"><span class="s1">Grandville lies in the tub, totally relaxed, sweating out the beer, and thinks philosophically once again. <em>Maybe it isn't necessary to work to enjoy this blissful state, </em>he counters. He reconsiders and decides not to show up to work tomorrow.</span></p>
                        <p class="p1"><span class="s1">Alice is a fast, efficient cook who invariably puts out more than is necessary at the dinner table. Grandville enjoys her meals and scarfs them up with zest. The kids are less appreciative, picky, and the middle boy, Renaldo, likes to whine. Grandville chides his stepson in his typical steady monotone voice.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Fifty years from to-day, Renaldo, there won't be any meat to eat on this planet, unless, maybe, Renaldo, you like the meat in cock-er-ro-chaahs. Things seem to be getting too easy around here, not enough ap-pre-ci-ay-tion. I think it is time we toughen up a little so things can be more ap-pre-ci-ay-ted.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Renaldo lowers his head and picks slowly at his baked potato. Only the sounds of knives and forks, and the gnawing inside one's mouth are heard.</span></p>
                        <p class="p1"><span class="s1">Grandville continues, &ldquo;Alice, just how important is money?&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice hesitates with thought, her fiery eyes increasing in intensity. She knows Grandville is up to something. &ldquo;Not so much, I guess, if you have some, but real important if you don't.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville gnaws on his steak and then with a big gulp replies, &ldquo;Then how come people who have a lot of money seem to get more and people who have little seem to get less? If it is more important to the poor and less important to the rich, then wouldn't money gravitate more toward an equal distribution&mdash;for all?&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice stabs at a broccoli, then decides not to place it in her mouth. &ldquo;I never thought of that before. That <em>is</em> strange.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville continues, &ldquo;Let's ask the question 'what does money do for people?'&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice leans back into her chair, forgetting the food. &ldquo;If you have lots of money you can do whatever you want.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville replies, nodding with each syllable, &ldquo;Ex-zact-ly. And at anyone's expense. If you have a lot of money you don't have to cooperate with nobody. People who don't like to cooperate go after money and get the most. People who like to cooperate don't fight for money as hard. So the cooperative ones get less and the greedy get more and then the greedy use that money to get even more. They don't care who they trample to get it because they are uncooperative by nature and when they get money because they are uncooperative, they don't mind-dah crushing the cooperative people. The uncooperative say, &lsquo;I'm rich now. I can do what I want. I don't need you anymore.'&rdquo;</span></p>
                        <p class="p1"><span class="s1">Josephina, Renaldo and Teddy bow their heads and poke at their food. They know what is coming. Grandville is beginning another one of his famous philosophical tirades.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Here in America the Indians helped the Pilgrims survive the First Thanksgiving. Then fifty years later when the gringos were stronger and didn't need the Indians, they just massacred them to get richer. Even the great King Cuauhtemoc, who had put down the Spaniards, kicked them out of his territory, and when they moaned about their lot and the trouble they would get in with their King, he tried to cooperate with the gringo, give them a little gold if it seemed so important to them. Instead the gringo took all the money, the money of a whole empire and then to thank Cuauhtemoc, Cortez, the gringo, just went and killed Cuauhtemoc. &lsquo;Ha Ha,' says Cor-tez, &lsquo;You stupid. You tried to cooperate.'&rdquo;</span></p>
                        <p class="p1"><span class="s1">Teddy, the youngest at eight years old, stabs his steak. &ldquo;We, La Raza, need to wipe out the gringo.&rdquo;</span></p>
                        <p class="p1"><span class="s1">&ldquo;Then we would be like the gringo, Teddy, uncooperative,&rdquo; replies Grandville.</span></p>
                        <p class="p1"><span class="s1">Not liking the way the conversation is going, Alice interrupts. &ldquo;Grandville, what do you suppose we should do?&rdquo;</span></p>
                        <p class="p1"><span class="s1">&ldquo;We need to teach the gringo how to be cooperative,&rdquo; replied Grandville.</span></p>
                        <p class="p1"><span class="s1">Teddy's face is turning red and his eyes are glaring. &ldquo;And how do you suppose we could do that, Grandville?&rdquo;</span></p>
                        <p class="p1"><span class="s1">&ldquo;If money attracts uncooperative behavior, we simply need to eliminate money.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Josephina, the oldest at twelve years old, bolts up to a standing position. &ldquo;That's impossible, Grandville.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville smiles. &ldquo;Maybe not, Josephina, maybe not.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice drops her fork. She knows that Grandville's words are immediately carried into action. Grandville is going to destroy money!</span></p>
                        <p class="p1"><span class="s1">Grandville continues, &ldquo;But we must take this step-by-step. First we have to experiment, live without money, see if we can be more appreciative and more cooperative without money. If it works, we will pass it on to the gringo.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice gags on her steak. If the whole world had come up with such an idea, Alice would have had nothing to do with it. But Grandville was different. He was a miracle worker. When she at last clears her throat, she says, &ldquo;Sounds like an interesting experiment, Grandville.&rdquo;</span></p>
                        <p class="p1"><span class="s1">&ldquo;Indeed, indeed,&rdquo; replies Grandville.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Sounds like this is the experiment that is going to make you world famous, Grandville.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville responds, &ldquo;Oh I think so, I think so.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Renaldo makes a silent pledge never to be picky about his food ever again.</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">***</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">Grandville normally gets up at three every morning and works in his laboratory before catching the bus to his day job at the Department of Water and Works. But his excitement over his new experiment causes him to wake earlier this morning.</span></p>
                        <p class="p1"><span class="s1">He cautiously puts his left foot on the floor, then his right, lifting himself slowly. He then dresses and carefully waddles in his typical robot manner, eyes always checking the floor, towards the kitchen. Putting some coffee on, he starts stumbling around looking for the electronic wand, his key to his three-story, underground laboratory. Worried, not finding it in his usual hiding place in the ceiling, he stumbles around looking.</span></p>
                        <p class="p1"><span class="s1">Alice hears his fumbling and knows he has once again lost his wand. Putting on her robe, she carefully scans each room of the house on her way to the kitchen, finally locating the wand on the side of his rocking chair. He shows a smile of relief as she holds it up. She notices that the coffee does not have the right ratio of water to grounds and so empties its contents and makes a new pot. She is aware it is not time to talk; Grandville's mind is already in his laboratory working on his new experiment.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Go to the laboratory, my love. I'll bring you your coffee when it is ready.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville smiles thanks, then ever so cautiously waddles out to the patio. Pressing the wand to open the secret door to the laboratory, he releases his newly created force field, leaving it open for Alice and coffee. Gradually he descends; first his left foot takes a step, then his right foot gradually descends to the same stair. This is the way Grandville progresses downstairs.</span></p>
                        <p class="p1"><span class="s1">He arrives at the first floor. It is here in this room, hanging from the ceiling<span class="Apple-converted-space">&nbsp; </span>Grandville never did like putting things on the ground&mdash;that swings his model of the hydrogen atom with its twenty-two cubic and rectangular and triangular prism like mirrors, and its violet inner-space pyramid, formed by the trapped light and sound resonance within its nucleus.</span></p>
                        <p class="p1"><span class="s1">Like a feather, Alice descends the stairs. The darkened room is filled with rainbow images as the prism mirrors rotate, creating pulsating illusions.</span></p>
                        <p class="p1"><span class="s1">&ldquo;It is beautiful,&rdquo; she whispers.</span></p>
                        <p class="p1"><span class="s1">Grandville smiles. &ldquo;Beautiful but strange.&rdquo;</span></p>
                        <p class="p1"><span class="s1">&ldquo;Just like our world, Grandville. Just like our world.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville loves this woman.</span></p>
                        <p class="p1"><span class="s1">Alice places the coffee pot and cup upon the shelf, then steals herself up the stairs through the backyard into her bed as rainbow visions of Grandville's hydrogen atom play in her head.</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">***</span></p>
                        <p class="p3">&nbsp;</p>
                        <p class="p1"><span class="s1">It's eight o'clock and Grandville has not surfaced from his laboratory. Alice guesses, after their conversation at the dinner table last night that Grandville does not intend to work for the Department of Water and Works anymore. She decides that if they are not going to have an income she might pay more attention to the garden. So she goes to the store to buy seed.</span></p>
                        <p class="p1"><span class="s1">Her work continues long into the afternoon and Grandville still has not surfaced. Near dinnertime, he at last appears, climbing in through the boys' window while the kids play with their Lincoln Logs. Grandville's sudden appearance through the window turns the kids on like a sped-up movie. They drag him in and Josephina declares him to be King Kong threatening their Lincoln Log city.</span></p>
                        <p class="p1"><span class="s1">Grandville plays docile as they tie him to the bedpost, growling occasionally like King Kong. But suddenly he becomes emotional when the kids start to try to pull his extraordinarily sensitive big right toe.</span></p>
                        <p class="p1"><span class="s1">Kids squealing with delight and Grandville bellowing out in anticipated pain trying to protect his most sensitive big toe brings Alice to the rescue.</span></p>
                        <p class="p1"><span class="s1">Sizing up the situation, Alice courageously throws her body over Grandville's legs, covering up his toes. The kids are more conniving and start tickling their mother off Grandville and, at last, Josephina finds a vulnerable moment and yanks that big right toe.</span></p>
                        <p class="p1"><span class="s1">Grandville reacts with a sharp shriek and jumps high, unraveling the chains that bind him to the bedpost. Putting his hands straight out, palms up, he begs, &ldquo;Enough, enough!&rdquo; Alice stands between the kids and Grandville, gesturing the kids to calm down. The kids' squeals recede as Grandville begins another of his famous philosophical tirades.</span></p>
                        <p class="p1"><span class="s1">&ldquo;Why is it that nobody believes me, Josephina? I have told you time upon time again that my big toe is like a giant raw nerve. Just touching it sends shock waves through my entire system. Yanking it makes an earthquake in my body. Why don't you believe? The trouble with this world is that nobody believes. Everybody is second-guessing everybody else. If it hasn't happened to them, they assume the other person is lying, crazy, exaggerating, dumb or immoral. Even the Holy Bible. People, who witnessed the bread falling from the sky and the Red Sea parting, wrote it down. And now idiots who call themselves scholars 3,000 years later say what they wrote was only symbolic or a lie, or a myth or an exaggeration. None of these scholars accept the words at face value. Still those people were right there. They saw it. How can people second-guess what they say? Always remember the person closest to the event is in a hell of a better position to judge the event than you. I am in a hell of a better position to judge how my big right toe feels. Don't second-guess me anymore.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville's philosophical tirade is over.</span></p>
                        <p class="p1"><span class="s1">Josephina promises never to touch that toe again.</span></p>
                        <p class="p1"><span class="s1">A twinkle in Grandville's eye lets the kids know he is not mad anymore. He pulls Josephina to him and ruffles her hair as she hugs him. </span></p>
                        <p class="p1"><span class="s1"><span class="Apple-converted-space">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span>&ldquo;I'm sorry, Grandville. I'll never do that again.&rdquo;</span></p>
                        <p class="p1"><span class="s1">He smiles. &ldquo;Thank you, Josephina.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville is happy; he enjoyed his tirade. The kids are happy too; they are having fun. Alice is happy too, but she knows Grandville's every word is said with a purpose and the whole ten years she has known him, never before has he mentioned the Bible despite her futile efforts to encourage him to go to church. Something very special must have happened in his laboratory today. <em>But what?</em> she wonders.</span></p>
                        <p class="p1"><span class="s1">Grandville hobbles out of the room. In the den, he prepares a new sign slogan to hammer onto the living room ceiling. It says this: &ldquo;Gringo physics is based on the fantasy that if you pounce and pulverize something enough until it is utterly mauled and mutilated, then scrutinize its contorted debris, you will discover the secrets of the enormous cosmos.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice looks on as Grandville hammers his new sign into the ceiling. She knows this one must be very important for he places it almost exactly above his leather chair.</span></p>
                        <p class="p1"><span class="s1">Grandville gradually descends the ladder.</span></p>
                        <p class="p1"><span class="s1">Alice smiles. &ldquo;You must be starving.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville smiles and rubs an eye. &ldquo;Tired too, but first I need to walk to the bookstore before it closes. Can you hold dinner?&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice is shocked. Grandville has never liked walking; aside from walking about the house or to the bus stop or the half of block to Dick's Donut Shop, Grandville never walks.</span></p>
                        <p class="p1"><span class="s1">Grandville picks up a handful of physics books and starts to trudge to the used bookstore. Grandville would state many years later that he never trusted the ground. He knew the plus and minus electrical charge of the ground was not enough to keep his feet from falling through. The gravity vacuum cracks of our giant galaxy cluster combined with the gravity funnel people dwell within should shatter this electrical bond. Only when he discovered his void and mirror mechanics and added his time wave theory, which included the geometry of inner-space, did he feel comfortable walking. And that discovery culminated on this very day.</span></p>
                        <p class="p1"><span class="s1">At the bookstore, he trades his physics books for ancient Bibles.</span></p>
                        <p class="p1"><span class="s1">Grandville at last ascends the steps to his door, Bibles in hand. </span></p>
                        <p class="p1"><span class="s1">Alice opens the door as if she has a sixth sense that he was there.</span> <span class="s1">&ldquo;Dinner is ready. The kids are already fed and bedded down.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Grandville glances at the living room. Everything is tidy. Then he glances at the dinner table with candlelight and wine. This is one meal Grandville is going to relish.</span></p>
                        <p class="p1"><span class="s1">Alice is dying of curiosity, wondering what happened today in his laboratory but she decides to savor her curiosity until Grandville is ready to talk.</span></p>
                        <p class="p1"><span class="s1">Grandville is scarfing it up. Every once in a while he peers out of his food with the grin of a Cheshire cat. Hair unraveled, dressed in an awkward style more befitting a lumberjack, wearing combat boots that look like they have been through World War II, Grandville's appearance is in stark contrast to Alice's dinner, the table set in china, candlelight and her beautiful face on top of a soft, seductive red silk gown.</span></p>
                        <p class="p1"><span class="s1">Tummy-upped, Grandville leans back to enjoy the luxuries of wine and Alice. The evening passes until Grandville says, &ldquo;I'll dance you home.&rdquo;</span></p>
                        <p class="p1"><span class="s1">Alice places her hand within his. He draws her up to him and squeezes her as Grandville coaches her to the perfect spot within his arms. They dance to the humming of one Grandville's own songs, ever so gradually drifting to bed. Bibles on the table and Alice in his arms, Grandville figures he has made a few more good moves than bad moves on this, the first day of his new no-money experiment.</span></p>
                        <p class="p5">&nbsp;</p>
                <div>
            <div>
        <div>
    </body>
</html>