<?php

/* @var $this yii\web\View */

$this->title = 'The Radio Revolution';
use yii\helpers\Html;

?>
<!DOCTYPE html>
<html>
<body>
    <div class = "container">
        <div class = "title">
            <h3>
                The Radio Revolution
            </h3>
        </div>
        <div class = "row">
            <div class = "col-md">
                    <div class = "story">
                        <div class = "container col-md-4 spacer">
                            <?= html::img('images/RadioRevolution.png', ['alt' => "some", "class" => "img-responsive"])?>
                            </div>
                        <p><center>THE RADIO REVOLUTION<br />A NOVEL TO CHANGE AMERICA<br />AT LAST PUBLISHED<br />AVAILBE ON AMAZON, AT IDEA'S MUSIC AND BOOKS IN KAKAAKO, BOOK ENDS<br />IN KAIULA AND TALK STORY IN HANAPEPE KAUAI.<br />ALSO ON EBOOK AND KINDLE<br />AND NOW ON AUDIO BOOK NARATED BY SHERIFF NORM WINTER THROUGH<br />AUDIBLE.COM, ITUNES AND AMAZON.<br />THE BOOK!<br /></center> <br><br><br><br><br><br>
                            Danny Fall is a beloved DJ in Honolulu, but his maverick ways have him being ostracized from corporate radio. He flees town to the island of Kauai in rage and meditates in the wilds, considering what he should do next. During a sand storm he finds shelter with four homeless, young adults. They are discouraged. The world is a cold, unfeeling place to them. Instead they look for solace through the unseen, the spiritual world, unable to find work that offers self-worth here on Earth. There is one girl, Mandy, a beautiful twenty-year-old Samoan/Chinese and three young men: Gregory, a black singer in a reggae band, Bradley, a computer hacker on the lamb from New England, and Juan, a gunslinger, con artist/thief/forger from the slums of Brazil. Danny sympathizes with their situation and has a special affinity for Mandy, despite their 28-year- age difference. She is still innocent, not jaded to life like he is. The five bond and they join Danny on his dream to give the people a real democratic radio station where the listeners choose the music through a ballot system, implementing the format of the radio station Radio Free Hawaii of the nineites, AKA the Radio</p>
                        <p>Revolution. . And finally, they take the radio concept one step<br />further, struggling to stay on the air and finally to give America a real democracy through a simple amendment to the constitution of the United States of America. You want to know how radio came to suck? You want to know how we can change America into a real democracy? You want to know the real economic dilemma we are facing and how to change it? READ THE BOOK</p>
                        <p>SAMPLE: FIRST CHAPTER</p>
                        <p>CHAPTER ONE</p>
                        <p>MAYBE I DO HAVE A HEART</p>
                        <p>Kaua'i, October 25, 1989</p>
                        <p>I have an insecure wife. She says she loves me. Nevertheless, she just locked me out of the house and suggested I go to Hell. Why? I've been fired from seven jobs in eighteen months. It's not that I'm a lousy worker. I'm a great worker who sizes up the problem and goes about trying to fix it.</p>
                        <p>Problem is, my bosses are lousy workers who talk about the different meows of their cats or whose super hero can wallop the other guy's super hero, with absolutely no understanding to the fact the American political arena is about to push the non-wealthy over the cliff. Love is forever. But it has a bad habit of leaving the realm of forever when your consciousness realizes, &ldquo;I'm not here anymore.&rdquo; It might be just as well. If I stayed, my consciousness would be spewing out senseless muck. So the &ldquo;forever&rdquo; is there and I'm over here with a bunch of homeless people in a cement, camp ground in Polihale. Polihale Beach Park is a massive sand dune on a little island in the Pacific called Kaua'i. The island itself has a weird connection to other worlds that the rest of the planet is deprived of, and Polihale is at the ass end of that island. It's a heavy place of pathos swallowed in a deep rich beauty with blaring ocean waves that pound against godly mountains. Why do I say godly? The mountains look like two-thousand- foot totem poles with the faces of Gods carved on their tops. It is here that the lives of the Earth exit into other worlds. I know that sounds crazy, but it is a perfectly natural concept to the people of Kaua'i. And you can feel the exit of life as the waves beat against the two-thousand- foot totem poles of the gods. People call me a radical, which they misinterpret to mean I'm incorrigible, a rebel who is out to destroy their security. A radical, however, is a person that sees the problem and tries to find a way to fix it before the same people face a disaster that obliterates their security. I thought I could fix it in the business world, but here I am in Polihale realizing</p>
                        <p>the problem goes deeper. The root of the problem lies in the Constitution of the United States of America. What does a radical do when he's faced with changing the Constitution of the United States of America? This radical, drinks a beer, shouts out a few blasphemies to his friends or anyone who will listen, and then conveniently stuffs the disaster into the back of his mind. Some radical. I realized at age sixteen: radio is the way to change the world. Why? It's a sound alone medium. You hear a sound and your mind imagines the visuals that go with the sound. It excites your imagination. You hear music and your emotions are activated by the sound alone medium. If a DJ's voice sounds sincere, a warm intimacy between you and the DJ is felt. It's like you and DJ are in a room together. If you hear listeners talking on radio, you feel more a part of the radio world. If radio opens the door to all kinds of music and ideas, you feel a part of the world, listening to radio. My theory at age sixteen was that with radio you are stirred into actively listening and feeling part of the world. Your consciousness is suddenly wired to the world and you are a part of the whole, sharing your feelings and ideas with others. When enough people share ideas with each other, it becomes a snowball and ignites the whole world with motivating thoughts. Yes, utilizing your imagination in the midst of being a part of the world - that is a way out of the pit the world has put itself within. Radio could be the world's savior. Now, I'm reconsidering. What does a sixteen-year- old know? But then again, love won't save the world. Sorry, John Lennon. Love is forever and a great fix-it, but it wilts when consciousness yells, &ldquo;I'm not here anymore.&rdquo;</p>
                        <p>Money won't do it. Sorry, Rockefeller. Money attracts the uncooperative people who work harder to get it so they can do whatever they want, and what they want is to shit on the cooperative people. Religion won't do it. Sorry, Pope. Pledging allegiance to the invisible might make you feel better because it can't talk back, but when people get into a group and decide everybody has to think the same, imagination is crushed, and the larger the group, the worse part of the human nature ascends to the top. Politics won't do it. Same problem. The larger the group, the stupider it gets and political systems are huge. So I came to the conclusion at age sixteen: radio is the best way to change the world. When radio was vibrant in the thirties, forties, fifties and sixties, didn't Orson Wells' &ldquo;War of the Worlds,&rdquo; and Hitler's fanatical, emotional speeches combined with Churchill's emotional speeches, and the Beatles crushing the rigid views of the time leading to the Woodstock concert - didn't they all change the world? If you were there, you know radio certainly did change the world. Of course now radio is a limp rag you can't even wring out. And the culprit? I already mentioned that. It's the Constitution of the United States of America. It's cold out here on the beach and the wind just blew my belongings and my tent into the waves. Sand is stinging my face and blowing into my eyes and I am beginning to believe Kaua'i people are right: this is where the torture of the earth's life departs. Trouble is, a whole bunch of that life must have been blasted dead in some war or terror</p>
                        <p>act and its departure isn't too soothing. Yeah, and it is a six-mile hike back to the main road and then I've got to hope for the mercy of a speeding car zooming along in nowhere with this questionable visibility. Here I am, Mr. Nature, trying to rough it without a car so I can think the deep thoughts, like what is my place here on this planet amongst the planet's natural surroundings? Stupid. What was I thinking? Coming out to the wild surf without even a car? And three nights from now, here in Kaua'i, I've got to meet my stupid ass words head on. What have I gotten myself into? But there are cars here in Polihale. I'll take shelter under one until it decides to leave, then beg for a ride if it can tread out of the sand and find the main road in near- zero visibility. I slither under a four-wheel drive, but it is still cold and the wind and sand seem to find me there anyway. I cover my head with my shirt as the sand burns my belly. I hear noises, humans squealing, and some yelling verbiage, people shouting to others in a group. I assume they are saying to each other, &ldquo;Get in the car, quick!&rdquo; I hear pots and pans clanking against the cement alcove, preparing to head for the ocean, and the tarp roof of the alcove is flapping loudly over the howling wind. The car rocks a bit and the engine starts. Oops. Dumb idea, getting under it. But it doesn't move. They just turned on the heater. I should get in the car.</p>
                        <p>I belly crawl out and knock on the door. The door opens. &ldquo;You poor man, you don't even have a jacket, jump in.&rdquo; I hesitate. The front is a two seater. A girl pulls me in anyway. She's a pretty one, and the driver looks like a Don Juan. In the back are two glassy-eyed young men, one with dreads, the other with dirty sandy-blonde hair and a snarled beard. The girl puts her arm around me, &ldquo;Don't take it wrong, I just want to get you warm. My name is Mandy.&rdquo; I'm out of her league anyway. I'm pushing fifty. &ldquo;Hey, this is the best welcome I've had in a long time, thank you!&rdquo; Mandy is beautiful at second look: a full figure, bronze flesh, probably a mixture of a thousand cultures and races and her brown eyes seem to flash into amusement, then solace, then a dreamy distant look. When her eyes are dreamy it is like she isn't even there. I know that look, it is the sign of intelligence as if, why am I here? I belong somewhere else. Now she smiles like she is the sun itself. Damn, I wish I was younger! Mandy says, &ldquo;Are you one of those lost ones looking? Show me your hand. I read palms. Left one first; that's your past.&rdquo; I show her my left. Don Juan says, &ldquo;She's really good, you know.&rdquo;</p>
                        <p>I'm trying to figure out why she thinks I'm a &ldquo;lost one.&rdquo; She says, &ldquo;Straight as an arrow, your heart.&rdquo; She's wrong about that. I feel pretty close to heartless now. &ldquo;You have the triangle. You will never leave Hawaii.&rdquo; She's right about that. I came here twenty-five years ago and even being forced to live in the streets a spell, I was determined to stay. &ldquo;You've got the elliptical cross. You're an earth shaker.&rdquo; I smile. &ldquo;I guess people might say that about me.&rdquo; She is still hugging me. I am getting a rise. I am really feeling her presence and really, really liking it. She reaches for my right hand. &ldquo;Gosh,&rdquo; her eyes light up. &ldquo;You are starting a new life, a famous one; you are going to be bigger than the movie stars.&rdquo; Thought that myself, but at the moment I had pretty much given up on it. But here, now, I'm a homeless middle-aged man barging into a car in a raging sand storm, and this girl has sized me up pretty well. Yeah, she is right about me starting a new life. And I sure am thinking of some big ideas. Maybe she is good with this fortune stuff. She looks at me very curious and intently. &ldquo;What do you do?&rdquo; I didn't want to tell these kids my vocation. Kids know radio sucks. &ldquo;Trying to make radio not suck, but failing miserably.&rdquo; I lift my hands in an act of hopelessness, &ldquo;That's what brought me here.&rdquo;</p>
                        <p>The dread in back, in a half laugh, says, &ldquo;How can you possibly make radio not suck?&rdquo; I was on the defensive. I forgot about the girl's arm around me and turned around facing the Dread in the back seat next to the Sandy one. &ldquo;By allowing people to have a real radio station. A radio station for the people, not for a bunch of idiot conglomerates who want everything to sound the same and then try to shove that sound down your throat. It is even in the 1934 preamble to the Congress's Radio Act. But in 1969 after Woodstock, the preamble for the people was eliminated by Congress, and radio has sucked ever since, in fact it gets suckier every year, if that's possible.&rdquo; The Sandy in the back smiles, &ldquo;Wow.&rdquo; The girl presses against me and kisses my cheek. &ldquo;I love you.&rdquo; She didn't mean it the way I wanted it to mean but I got a boner anyway. Don Juan seems a little uncomfortable. I divert the situation with a question, &ldquo;What's your name, driver?&rdquo; &ldquo;Why you ask?&rdquo; &ldquo;My name is Danny, Danny Fall.&rdquo; That is my stage name. My real name is Danny Boy Heinzwaffle. But I would never mention that name to anybody. &ldquo;I told you who I am. Why not you?&rdquo; &ldquo;I'm from Brazil.&rdquo; I gave a little room, &ldquo;Then a traveler, right? Looking for something?&rdquo;</p>
                        <p>&ldquo;Yeah, I've found it.&rdquo; He puts on his possessive pose. His arm and hand loops around Mandy, grabbing her shoulder. Mandy is the one who looks disturbed now. The Sandy one in the back tries to cool the tension. &ldquo;We are all just friends here, trying, struggling, to find ourselves in this fucked-up world.&rdquo; Mandy smiles to the back voice. Don Juan smiles saying, &ldquo;Yeah, that's the way it is, but a woman needs to be one with her man.&rdquo; A man doesn't need to say that unless he is not one with his woman. But I don't dare extend that logic. Mandy turns to Don Juan saying, &ldquo;I'm glad I'm helping you and you helping me, it is just the world is bigger than two people.&rdquo; Suddenly it is me who wants to say to Mandy: Jesus, I love you. While Don Juan is clinging to her, she is gripping my ribs harder than before. I'm thinking, I know of women who want to take on the world, to be fair to everybody, to give of themselves freely and who in the end go through torment that jades them for life. I suddenly don't want that to happen to Mandy. I want to keep her light going. God knows mine died so many years before. I'm desperate. I want hers to shine forever. Shit, There's that love word again. Forever. I throw it out there. &ldquo;About ten miles down the big road is a nice bar and restaurant. If you can find a way to get there, I'll treat you all. Till this storm winds down.&rdquo; The sandy-haired guy in the back says, &ldquo;You want some weed?&rdquo;</p>
                        <p>I figured it was a test to see if I was cool. &ldquo;Hey, I am a square, no interest in altering my mind except maybe calming it and making my emotions come to the surface with booze. You smoke, fine. Not me.&rdquo; Mandy takes a hard look at Don Juan. &ldquo;He's really trying to do something.&rdquo; The Dread in the back says, &ldquo;Cool it Juan, he just offered us a free meal. Can't be that bad.&rdquo; Shit, his name is really Juan. Juan takes the car out of park, the four-wheel- drive spins. We jump ahead a bit, but then slip back. He revs the car again, we jump again. I hear the motor screaming then popping as it sucks out the sand. We suddenly scoot forward. I hear the rumble as the car finds the dirt road. I use the word &ldquo;road&rdquo; loosely, even at five miles an hour I feel like we are in an earthquake. Mandy's arm is still clinging to my ribs. She whispers, &ldquo;I can feel your heartbeat.&rdquo; Her right breast is next to it. Juan doesn't notice, his eyes are focused on the so-called road a bit obscured by the sand storm. I keep up the banter to get everybody's mind off the tension. The outside sand flurry, the howling wind and the lack of visibility might help divert the tension, as well. &ldquo;Do you know what youth say when I ask what kind of music do you like?&rdquo; There's no answer. I go on. &ldquo;They seem to fight the question. Frequently, more than half the time, they stammer and finally say stuff like, &lsquo;I like all kinds of music.'&rdquo;</p>
                        <p>Tension is still churning. Mandy tries to put her head on my shoulder. It hits and bounces back with each pot hole in the road. Her right breast is still adjacent to my pounding heart. I reiterate, &ldquo;They fight the question and instead say all kinds of music.&rdquo; She says. &ldquo;Are you a radio programmer?&rdquo; &ldquo;I'm a consultant now, and consultants do research. And yeah, three out of four males 18-24, when I ask what kind of music they like, respond, &lsquo;I like all kinds of music,' or something to that effect. Why do they do that? Anybody here got an answer?&rdquo; There was silence. Yet I kept silent. Oddly it was Juan who first responded. &ldquo;Because they don't have any fucking idea of how much different music is out there. If they heard some of it, they would call a lot of it shit.&rdquo;</p>
                        <p>I smile. Ah, got him talking. As always I'm a bad ass trying to get to the bottom of things. I say, &ldquo;True, but why fight the question? Can't they say stuff like, I like reggae and pop or rock, but no, they insist in saying stuff like any kind, or all kinds of music, despite the question being what kind of music do you like?&rdquo; Sandy in the back jumps in, &ldquo;Well, two out four 18-24s' probably don't have any real taste when it comes to music, it is just blah, all the same.&rdquo; I keep pushing. &ldquo;It's very odd for 18-24s not to be opinionated about the music they like. They are in the final process to find out who they are and music, for most, is</p>
                        <p>one of the identifiers. Nevertheless, when asked directly what kind of music do they like, it is like they don't even listen to the question, they respond, 'All kinds.'&rdquo; Mandy says, &ldquo;Maybe they don't want to be categorized. You are already categorizing them by putting them in blocks of ages. Maybe they are fighting the survey.&rdquo; &ldquo;That's a slither of the truth,&rdquo; I say. &ldquo;But it goes deeper. We are living in an age where free enterprise is being suffocated by massive conglomerates trying to completely control the market. They make their employees follow strict guidelines, they give them little chance to find personal identity through their work, and youth has a real hard time jumping into that world. Even free enterprise feels the pressure to act the same now. You are right, Mandy, they don't want to be categorized, especially males 18-24 in my research. They are screaming to bust loose.&rdquo; Mandy says, &ldquo;I'm nineteen, and a girl, I sure don't want to be categorized in a survey.&rdquo; Sandy, in the back, says, &ldquo;Hey Danny, you might be on to something. I feel out of place in this world, like where can I get involved? I'm twenty-six, and sure I like reggae but I might answer 'all kinds,' too. I like variety.&rdquo; Juan jumps in, &ldquo;The world sucks, the spiritual way is all that there is left. We need to lift ourselves up in spirit to get away from this hell.&rdquo; Mandy squeezes his hand in approval. The Dread is silent but when I turn to him, I detect his approval. I'm crying inside. I remember what it was like when I was a kid. Jobs everywhere. You were treated like an individual having a chance to find yourself in your</p>
                        <p>work. Then twenty years later in the eighties, conglomerates overran free enterprise and started controlling the market. The workers have to follow strict guidelines or be fired for any slight deviation. And when conglomerates get a certain size they go on runaway, they can make a slew of mistakes to lose profit and still they rumble on. If you want to improve the situation, they just dump you because being a big shit is more important than creating value in the market place anymore and improving profit. Twenty-five years later, the kids aren't even trying. It is so hopeless. They'd rather search for the invisible than deal with Earth. This stuff is hitting me like daggers. I'm crying. Maybe I do have a heart.</p>
                        <h1>
                            <?= html::a("The History of Rock'N'Roll for Extraterrestrials", "http://www.ideasmusicandbooks.com/sheriff-norm-on-the-air");?>
                        </h1>
                        <h4>
                            How radio came to suck
                        </h4>
                    </div>
                <div>
            <div>
        <div>
    </body>
</html>